### ISSUE TITLE
(Hybrid) Spotlight: Light mode, selected item not visible

### ISSUE THREAD

**Issue by maciboy** [SpiraMira/HybridMode-Public#11] opened 2018-11-12 14:23 UTC
Hey,
there is another issue I’m experiencing and was hoping it might be fixed in hybrid v1.3 ;)

When using spotlight, I can’t read the selected result:
![bildschirmfoto 2018-11-12 um 15 13 30](https://user-images.githubusercontent.com/19333006/48353032-aef77e80-e68e-11e8-8f75-ef619dd5d7ae.png)

(Luckily the item-text is also displayed in the search field^^)

Running 10.14.1 btw

Thanks!

**Comment by SpiraMira** [comment] 2018-11-12 18:53
Unfortunately, I didn't get around to doing so.  I'll check this out later today.

**Comment by maciboy** [comment] 2018-11-12 19:02
Sorry, this was not meant to be a claim for instant repair...
Take your time, I can live with that, just wanted to mention it 😜

**Comment by ptkovsky** [comment] 2018-12-01 08:13
Hello. Thanks for doing this! A fix would be definitely appreciated since it is also happens in other Apple software like Safari for example, address and search bar dropdown list lacking readability and it's kinda annoying to use.

**Comment by SpiraMira** [comment] 2018-12-12 15:21
Should not be the case.
- What machines and video cards are you using? A relevant snapshot of your system software cpu and display section will help.
- I'm assuming you have a 10.14.1 + v1.3 configuration, If not advance to 10.14.2 and try v1.4

**Comment by SpiraMira** [comment] 2018-12-13 05:20
I can confirm your bug.  Slipped through, sorry.  I'm not sure if it's something different (overlooked) in 10.14.2 or my fat fingers... Stay tuned.

**Comment by SpiraMira** [comment] 2018-12-13 06:53
Just a heads up. A fix has been found and is scheduled for v1.4.1 of CoreUI(Hybrid).

**Comment by SpiraMira** [comment] 2018-12-14 06:20
Please try the following: A pre-release of CoreUIHybrid that should fix: 

Spotlight:
- background is vibrant in both dark and light
- selections are back to visible (using the default selection material - usually blue)

Menubar: 
- menubar titles on the right are rendered correctly when either the title or menu items are selected.

Installation is simple: unzip - replace CoreUI in /S/L/PrivateFrameworks with the new binary

If ok. I will release as 1.4.1

Thanks.
[CoreUIHybrid-18C54-v1.4.1.zip](https://github.com/SpiraMira/HybridMode-Public/files/2678863/CoreUIHybrid-18C54-v1.4.1.zip)

**Comment by ptkovsky** [comment] 2018-12-14 09:42
Looks fine for me at first glance, didn't test much, but seems like no more white (unreadable) selections. Let's wait for some detailed feedback from others. Cheers!

**Comment by maciboy** [comment] 2018-12-14 12:04
Can confirm :)))
Tested (in dark & light):
-Spotlight: selection is blue
-Safari address bar: selection is blue
-menubar: icons are visible when selected

Nice job, thanks a lot!

**Comment by SpiraMira** [comment] 2018-12-14 14:59
Ok.  Thanks for testing the pre-release!

**Closed as completed** 2018-12-14 16:45 UTC
Labels: bug
